// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pogdrjzralwigkrbjgwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZ2RyanpyYWx3aWdrcmJqZ3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzgwMzQsImV4cCI6MjA2MDcxNDAzNH0.0KrXBSkVvsfQPMWCJk6bCIoc08qzR_SuCAJbrRL_C2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);